/* generated by Svelte v3.32.3 */
import { SvelteComponent, init, safe_not_equal } from "svelte/internal";

import { writable } from "svelte/store";
const count = writable(0);

class Component extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Component;
export { count };